# Generated by Django 3.2.8 on 2021-11-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discription',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
