# Generated by Django 3.2.8 on 2021-12-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_profile_image', upload_to='profile_image'),
        ),
    ]
