# Generated by Django 3.2.8 on 2021-10-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211009_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublisherModel',
        ),
    ]
