# Generated by Django 3.2.8 on 2022-01-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='discription',
            new_name='bio',
        ),
    ]
