# Generated by Django 3.2.18 on 2023-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/default_profile_image.jpg', upload_to='profile_image'),
        ),
    ]
