version: '3.7'

services:
  django_gunicorn:
    
    volumes:
      - static:/static 
    env_file:  
      - .env
    build:
         context: .
    ports:
      - "8000:8000" 
  
  
  nginx:
    
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - django_gunicorn    

volumes:
  static: