# Generated by Django 5.0.8 on 2024-12-09 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_cartservercomponentitemmodel_cartserveritemmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartserveritemmodel',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CartServerItemModel_User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
