# Generated by Django 5.0.8 on 2024-12-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_cartserveritemmodel_buyer'),
        ('components', '0005_servermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartserveritemmodel',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CartServerItemModel_ServerModel', to='components.servermodel'),
            preserve_default=False,
        ),
    ]
