# Generated by Django 3.2.8 on 2021-10-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20211019_0958'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('cover', models.ImageField(default='default_category_cover.jpg', upload_to='category_cover')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(default='default_cover.jpg', upload_to='components_cover')),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GameModel_CategoryModel', to='components.componentcategorymodel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComponentsModel_OrganisationModel', to='games.publishermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='VendorModel',
        ),
    ]
