# Generated by Django 3.2.8 on 2021-10-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20211019_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentcategorymodel',
            name='cover',
            field=models.ImageField(default='default_category_cover.jpg', upload_to='component_category_cover'),
        ),
        migrations.AlterField(
            model_name='componentsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ComponentsModel_ComponentCategoryModel', to='components.componentcategorymodel'),
        ),
    ]
