# Generated by Django 3.2.16 on 2023-04-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_cartcomponentitemmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartComponentItemModel',
        ),
    ]
