# Generated by Django 5.0.8 on 2024-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_delete_cartcomponentitemmodel'),
        ('games', '0014_remove_gamesmodel_profile_picture_gamesmodel_box_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('uptime', models.PositiveIntegerField()),
                ('price_per_hour', models.PositiveIntegerField()),
                ('components', models.ManyToManyField(related_name='server_ComponentsModel', to='components.componentsmodel')),
                ('pre_installed_game', models.ManyToManyField(related_name='server_GamesModel', to='games.gamesmodel')),
            ],
        ),
    ]
