# Generated by Django 3.2.8 on 2021-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('cover', models.ImageField(default='default_category_cover.jpg', upload_to='category_cover')),
            ],
        ),
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cover', models.ImageField(default='default_cover.jpg', upload_to='games_cover')),
                ('price', models.PositiveIntegerField()),
                ('discription', models.CharField(max_length=500)),
                ('sale', models.BooleanField(default=False)),
                ('release_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
    ]
