# Generated by Django 3.2.8 on 2021-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cover', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
