# Generated by Django 3.2.8 on 2021-10-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_publishermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
