# Generated by Django 3.2.8 on 2022-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_categorymodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmodel',
            name='about',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='organisationmodel',
            name='username',
            field=models.CharField(default='sadasad', max_length=20),
            preserve_default=False,
        ),
    ]
