# Generated by Django 3.2.8 on 2021-10-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_publishermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.categorymodel'),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publishermodel'),
        ),
    ]
