# Generated by Django 3.2.16 on 2023-03-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20220122_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameImageModel_GameModel', to='games.gamesmodel')),
            ],
        ),
    ]
