# Generated by Django 3.2.8 on 2021-10-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20211012_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
