# Generated by Django 3.2.16 on 2023-03-31 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_gameimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoughtModel',
            new_name='CartItemModel',
        ),
    ]
