# Generated by Django 3.2.16 on 2023-04-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_boughtmodel_cartitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmodel',
            name='logo',
            field=models.ImageField(default='organisation_logo/default_organisation_logo.jpg', upload_to='organisation_logo'),
        ),
    ]
