# Generated by Django 3.2.16 on 2023-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_organisationmodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmodel',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmodel',
            name='logo',
            field=models.ImageField(default='organisation_logo/default_organisation_logo.png', upload_to='organisation_logo'),
        ),
    ]
