# Generated by Django 3.2.8 on 2021-10-19 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_categorymodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishermodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PublisherModel_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BoughtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoughtModel_User', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoughtModel_GamesModel', to='games.gamesmodel')),
            ],
        ),
    ]
