# Generated by Django 3.2.16 on 2023-04-02 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0009_auto_20230401_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItemModel',
            new_name='CartGameItemModel',
        ),
    ]
