# Generated by Django 3.2.19 on 2024-01-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_delete_cartgameitemmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesmodel',
            old_name='discription',
            new_name='description',
        ),
    ]
