# Generated by Django 5.0.2 on 2024-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_rename_discription_gamesmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='games_profile_picture'),
        ),
    ]
