# Generated by Django 5.0.2 on 2024-03-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_gamesmodel_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesmodel',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='gamesmodel',
            name='box_art',
            field=models.ImageField(default='default_box_art.jpg', upload_to='games_box_art'),
        ),
    ]
