name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: create .env
        run: mv template.env .env

      - name: Build and start Docker containers
        run: docker compose -f docker-compose.yml up -d --build
      
      - name: Wait for Django to start
        run: |
          timeout=60
          start_time=$(date +%s)
          while true; do
            echo "checking if Django is ready..."
            if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8000)" == "200" ]]; then
              break
            fi

            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))

            if [[ $elapsed_time -ge $timeout ]]; then
              echo "Timeout reached. Django did not start within $timeout seconds."
              exit 1
            fi

            sleep 5
          done

      - name: Run Django tests
        run: docker exec gecom_django python manage.py test

      - name: Stop and remove Docker containers
        run: docker compose down
